min_version = "2026.4.8"

[settings]
install_before = "1d"

[tools]
biome = "2.4.13"
bun = "1.3.14"
node = "24.16.0"
"npm:@endevco/aube" = { version = "1.16.1", npm_args = "--ignore-scripts=false" }

[task_config]
includes = [
  "git::https://github.com/iwamot/mise-tasks.git//.mise/tasks?ref=v2.4.0",
]
