min_version = "2026.4.8"

[settings]
install_before = "1d"

[tools]
biome = "2.4.13"
bun = "1.3.13"
node = "24.15.0"
"npm:@endevco/aube" = "1.10.0"

[task_config]
includes = [
  "git::https://github.com/iwamot/mise-tasks.git//.mise/tasks?ref=v2.3.0",
]
