name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-node.yml@3fea0df39d8fefbf8eebd385aac85cd09a3faa57 # v3.3.0
    with:
      node-versions: '["20","22","24"]'
