name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  per-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node: ['20', '22', '24']
    permissions:
      contents: read
    env:
      MISE_NODE_VERSION: ${{ matrix.node }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          experimental: true
          cache: false
          install: false
      - run: bash compatibility.sh

  compatibility:
    needs:
      - per-node
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions: {}
    steps:
      - run: 'true'
