name: Publish

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          experimental: true
          cache: false
      - run: aube install --frozen-lockfile
      - run: |
          VERSION="${GITHUB_REF_NAME#v}"
          npm pkg set version="$VERSION"
      - run: aube run build
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --provenance --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
