name: Publish

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          experimental: true
          cache: false
      - run: aube install --frozen-lockfile
      - run: |
          VERSION="${GITHUB_REF_NAME#v}"
          npm pkg set version="$VERSION"
      - run: aube run build
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --provenance --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
