name: Publish

on:
  push:
    tags: ['v*.*.*']

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-npm:
    name: publish-npm
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    permissions:
      contents: read
      id-token: write  # for npm Trusted Publishing OIDC
    steps:
      - uses: iwamot/actions/npm-publish@792bb6f7b66b5d046aa285d39303a0aa7b10f822 # v0.5.0
